config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'session/new'

  root                'static_pages#home'
#  get '/home',    to: 'static_pages#home'
  get '/causeries',	to: 'static_pages#causeries'
  get '/letopo',   to: 'static_pages#letopo'
#  get '/links_form', to: 'links#form'
  get '/comment', to: 'static_pages#comment'
#  get '/home', 		to: 'static_pages#home'
  get '/fabrique', 		to: 'static_pages#fabrique'
  get '/signup', 	to: 'users#new'
  post '/signup', to: 'users#create'
#  get '/links',   to: 'links#show'
  post '/links',  to: 'links#create'
  get '/login',		to: 'session#new'
  post '/login',	to: 'session#create'
	delete '/logout',	to: 'session#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :microposts,         only: [:create, :destroy, :index]
  resources :relationships,       only: [:create, :destroy]
  resources :links
  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def letopo
  end

  def home
    if logged_in?
      render 'landing'
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    else
     render 'landing'
    end
  end

  def fabrique
  end

  def causeries
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/causeries.html.erb
<% provide(:title, "causeries") %>
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %></title>
</head>
<body>
	 <h1>causeries</h1>
</body>
</html>

app/views/static_pages/comment.html.erb
<h2 style="margin-bottom: 20px">_faq</h2>

<div class="container background">
		<li>
  			<button type="button" data-toggle="collapse" data-target="#faq1" style="background-color: white">faq > pourquoi se connecter ?
</button>
  				<div id="faq1" class="collapse" style="background-color: white">
   
    	Nous avons choisi de donner la possibilité de pouvoir poster du contenu sur orama sans avoir a être connecté, c’est-à-dire de laisser le choix de s’inscrire ou non. Tout le monde peut donc publier sur orama de façon anonyme. Toutes les publications envoyées de cette manière ne seront plus éditables, puisque si tout le monde pouvait modifier des contenus de façon anonyme, un troll aurait vite fait de mettre en l’air le site. C’est pour cette raison que nous avons donné la possibilité de créer des comptes, qui vous permettent de garder une trace de ce que vous publiez sur le site et de pouvoir les modifier. 

  				</div>
  		</li>
  		<li>
  			<button type="button" data-toggle="collapse" data-target="#faq2" style="background-color: white">faq > à quoi sert le pad des causeries ? 

</button>
  				<div id="faq2" class="collapse" style="background-color: white">
   
    	Le pad des causeries est un éditeur de texte à plusieurs et libre. Comme un gros bloc notes collectif, ce pad n’a pas pour objectif d’être un lieu de rédaction de choses arrêtées, c’est au contraire une page sur laquelle vous pouvez faire des propositions pour les causeries à venir : suggérer des sujets à aborder, des formes, des lieux, des invités, etc. 

  				</div>
  		</li>
  		<li>
  			<button type="button" data-toggle="collapse" data-target="#faq3" style="background-color: white">Faq > Pourquoi des mots de passe ?

</button>
  				<div id="faq3" class="collapse" style="background-color: white">
   
    	Dans Utopie du logiciel libre, (http://lepassagerclandestin.fr/fileadmin/assets/catalog/essais/Utopie_logiciel_libre__Broca__Le_passager_clandestin.pdf) Sébastien Broca raconte un épisode de la vie de Richard Stallman, l’inventeur du logiciel libre, confronté à l’apparition des premiers mots de passe : « En parallèle à l’écriture de lignes de code, Richard Stallman ne cessait de défendre l’ouverture de tous les logiciels et ordinateurs utilisés au sein du laboratoire. Il lutta notamment contre l’introduction de mots de passe, que de nombreux enseignants du MIT (notamment au sein du laboratoire concurrent, le Laboratory for Computer Science) se mirent à défendre à la fin des années 1970. Suite à l’installation en 1977 d’un tel système de sécurité, Richard Stallman contre-attaqua conformément à la tradition hacker de l’action directe. Il modifia le code source du système, de sorte que le message suivant apparaisse dès qu’un utilisateur entrait son mot de passe : « Je vois que vous avez choisi le mot de passe “x”. Je vous suggère d’utiliser le mot de passe “Entrée”. Plus facile à taper, il démontre le caractère illusoire des mots de passe et de la sécurité ». Bien qu’elle connût pendant un temps un certain succès, la campagne de Richard Stallman fut finalement mise en échec : en 1980, tous les ordinateurs du MIT avaient été munis de systèmes de sécurité. » (pages 47-48)

Si les mots de passe étaient, au début du web, une pratique restrictive et tristement sécuritaire, ils sont malheureusement devenus aujourd’hui indispensables. Ce sont eux qui posent une première barrière contre l’espionnage et le piratage de vos données personnelles. Selon Edward Snowden, interrogé par le présentateur américain John Oliver en 2015, « Les mauvais mots de passe sont un des moyens les plus faciles pour hacker un système. Pour quelqu'un qui a un mot de huit caractères très commun, cela prend littéralement moins d'une seconde pour un ordinateur le contourner. » (https://www.franceinter.fr/culture/faites-confiance-a-edward-snowden-changez-vos-mots-de-passe) Et si le même mot de passe se trouve être utilisé sur la plupart des sites que vous utilisez, il suffira d’un piratage via un de ces sites pour accéder dans la foulée à toutes les données protégées par ce même mot de passe : il ouvrira l’accès à l’ensemble de vos comptes, et pourra également impacter vos contacts (envois de mails piratés se faisant passé pour vous, etc).

  				</div>
  		</li>
  		<li>
  			<button type="button" data-toggle="collapse" data-target="#faq4" style="background-color: white">faq> comment supprimer mon compte ? 

</button>
  				<div id="faq4" class="collapse" style="background-color: white">
   
    	Pour supprimer votre compte, connectez-vous pour accéder à votre espace personnel, puis cliquez sur supprimer mon compte. 

  				</div>
  		</li>
  		<li>
  			<button type="button" data-toggle="collapse" data-target="#faq5" style="background-color: white">Faq> Une fois mon compte supprimé, que deviennent mes données ? </br>s’agit-il d’une vraie suppression ou simplement d’une désactivation ? 


</button>
  				<div id="faq5" class="collapse" style="background-color: white">
   
    	Une fois votre compte supprimé, l’ensemble de vos données, liens postés, sujets abordés etc, tout sera supprimé définitivement d’orama. Nous ne conservons aucune de vos données. 

  				</div>
  		</li>
  		<li>
  			<button type="button" data-toggle="collapse" data-target="#faq6" style="background-color: white">Faq > Utilisez-vous mes données ? 


</button>
  				<div id="faq6" class="collapse" style="background-color: white">
   Vos données ne circulent pas ailleurs que sur orama. Nous ne vendons vos données à personne. La revente des données personnelles est la façon dont procèdent une écrasante majorité de services propriétaires apparemment gratuits. Ils ne le sont pas, puisque nous payons à coups d’informations personnelles notre passage sur ces sites et autres logiciels. C’est contre cette monétisation de la vie privée, pour sa protection, et pour un internet libre, que nous nous positionnons avec orama. Le site Protège tes données (https://controle-tes-donnees.net/) propose plusieurs façons de reprendre le contrôle sur l’utilisation de vos données personnelles. Vous en trouverez d’autres dans le catalogue !


  				</div>
  		</li>

</div>

app/views/static_pages/fabrique.html.erb
<% provide(:title, "fabrique") %>
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %></title>
</head>
<body>
	 <div class="container">
	 	<h1 style="justify-content: center">Bientôt</h1>
	 </div>
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "home") %>
<!DOCTYPE html>
<html>
<head>
	<title> <%= yield(:title) %> </title>
</head>
<body>
	<% if logged_in? %>
		<div class="row">
			<aside class="col-md-4">
				<section class="user_info">
					<%= render 'shared/user_info' %>
				</section>
				<section class="stats">
					<%= render 'shared/stats' %>
				</section>
				<section class="micropost_form">
					<%= render 'shared/micropost_form' %>
				</section>
			</aside>
			<div class="col-md-8">
				<h3>remplis tes messages</h3>
				<%= render 'shared/feed' %>
			</div>
		</div>
	<% else %>
	<%= render 'shared/link_form' %>
	<div class="center jumbotron">
	 	<h1>Orama</h1>
    	<h2>
      		<a href="http://www.railstutorial.org/">orama</a>
    	</h2>
    	<%= link_to "s'inscrire", signup_path, class: "btn btn-lg btn-primary"%>
    </div>
    <% end %>
</body>
</html>

app/views/static_pages/landing.html.erb
<% provide(:title, "orama") %>
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %></title>
</head>
<body>
	<div class="container background" style="height: 200px;">
	<div class="block_l">
		<div class="block-head_l">
			<h2>orama</h2>
		</div>
		<div class="block-body_l">
			<p class="back_faq font_l">bienvenue sur orama !<br>
orama = suffixe des mots lié à la vue, <br>au fait de voir <a href="https://fr.wiktionary.org/wiki/-orama" class="ch_color_e">[https://fr.wiktionary.org/wiki/-orama]</a>
en et hors ligne, <br>orama regarde les outils libres et autres moyens alternatifs qui flirtent avec les pratiques artistiques.<br>
vous êtes donc ici sur la partie en ligne d'orama, où vous trouverez <br><b><%= link_to "le catalogue de liens", links_path, class: "ch_color_i" %></b>, <br><b><%= link_to "la fabrique des outils", fabrique_path, class: "ch_color_i"%>,</b> <br>et le programme <b><%= link_to "des causeries", causeries_path, class: "ch_color_i"%></b> (les causeries étant la partie hors ligne d'orama).
			</p>
		</div>	
	</div>
	</div>
</body>
</html>

app/views/static_pages/letopo.html.erb
<% provide(:title , "le topo") %>
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %></title>
	</head>
	<body>
		<div class="container">
			<div class="row background">
				<div class="col-md-4">
					<p class="back_faq faq2">orama regarde les moyens alternatifs de création artistique, commente, et comme d’autres avant, partage ses découvertes. 
Faire que le logiciel libre soit plus visible : qu’on en parle, qu’on l’utilise. Que l’utilisation de ces logiciels soient également reconnus dans le milieu du travail. 
Le logiciel libre permet une utilisation d’un outil qui respecte la protection de la vie privée de ses utilisateurs, rend perméable et accessible sa structure même, ouvre d’autres possibilités de créations que celles largement standardisées par l’usage de logiciels propriétaires (type suite adobe). 
Imaginer et fabriquer d’autres moyens de production, qui s’adapte au web, qui passent par le code. 
Initier aux logiciels libres, participer à les rendre plus visibles 
qu’on puisse choisir le logiciel qu’on utilise 
comprendre l’impact des outils et de nos passages sur internet 
orama ne traque pas 
ne revend pas les données 
orama regarde les moyens alternatifs de création parce qu’ils permettent d’envisager d’autres manières de faire, utiliser des outils qui respectent la vie privée, encourager la création et la compréhension des choses qu’on utilise, essayer des choses
orama cherche à apprendre
cherche à faire connaître 
cherche à causer 
cherche à fabriquer 
</p>
				</div>
				<div class="col-md-4">
					<p class="back_faq faq2">"En fait, le logiciel libre est doublement révolutionnaire. Il s'oppose en premier lieu à la logique qui consiste à privatiser la connaissance et l'usage pour maintenir les utilisateurs dans un état de dépendance et établir un monopole basé uniquement sur le non-partage d'un programme (c'est à dire du code issu d'un langage informatique la plupart du temps connu de tous)."</p>
				</div>
				<div class="col-md-4">
					<p class="back_faq faq2">Suprématie des GAFAM dans le monde de l’art :
initiation quasi systématique aux logiciels propriétaires : le logiciel libre est peu considéré dans les écoles d’arts, pourtant lieu de créations (création de l’outil, et création avec l’outil), et c’est sans ambivalence que les logiciels propriétaires sont installés sur les ordinateurs et vers lesquels l’enseignement se tourne très majoritairement. Pourtant, ces logiciels, par le fait même que leur structure (leur code) soit tenu fermé, restreint les possibilité de créations. Utiliser des outils que l’on puisse modifier. Comprendre le fonctionnement d’un outil pour ne pas être esclave de cet outil. Reprendre la main sur le processus même de fabrication de ses pièces. Puis, et surtout, visualiser l’impact de l’utilisation d’outils propriétaires sur nos données, c’est-à-dire sur notre vie privée </p>
				</div>
			</div>
		</div>
	</body>
</html>