config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'session/new'

  root                'static_pages#home'
#  get '/home',    to: 'static_pages#home'
  get '/causeries',	to: 'static_pages#causeries'
  get '/letopo',   to: 'static_pages#letopo'
#  get '/links_form', to: 'links#form'
  get '/comment', to: 'static_pages#comment'
#  get '/home', 		to: 'static_pages#home'
  get '/fabrique', 		to: 'static_pages#fabrique'
  get '/signup', 	to: 'users#new'
  post '/signup', to: 'users#create'
#  get '/links',   to: 'links#show'
  post '/links',  to: 'links#create'
  get '/login',		to: 'session#new'
  post '/login',	to: 'session#create'
	delete '/logout',	to: 'session#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :microposts,         only: [:create, :destroy, :index]
  resources :relationships,       only: [:create, :destroy]
  resources :links
  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			Le formulaire contient <%= pluralize(object.errors.count, "erreur") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<%end%>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %> 
	<div class="field">
		<%= f.text_area :content, placeholder: " ecrit ton message ;)" %>
	</div>
	<%= f.submit "Envoyer", class: "btn btn-primary" %>
	<span class="picture">
		<%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/jpg, image/png' %>
	</span>
<% end %>

<script type="text/javascript">
	$('#micropost_picture').bind('change', function() {
			var size_in_megabytes = this.files[0].size/1024/1024;
			if (size_in_megabytes > 5) {
				alert('La taille est limitée à 5MB. Choisit un fichier plus petit ;)')
			}
	});
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.following.count %>
		</strong>
		following <!--not in english for orama-->
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers <!--same shit for orama-->
	</a>
</div>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>