config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'session/new'

  root                'static_pages#home'
#  get '/home',    to: 'static_pages#home'
  get '/causeries',	to: 'static_pages#causeries'
  get '/letopo',   to: 'static_pages#letopo'
#  get '/links_form', to: 'links#form'
  get '/comment', to: 'static_pages#comment'
#  get '/home', 		to: 'static_pages#home'
  get '/fabrique', 		to: 'static_pages#fabrique'
  get '/signup', 	to: 'users#new'
  post '/signup', to: 'users#create'
#  get '/links',   to: 'links#show'
  post '/links',  to: 'links#create'
  get '/login',		to: 'session#new'
  post '/login',	to: 'session#create'
	delete '/logout',	to: 'session#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :microposts,         only: [:create, :destroy, :index]
  resources :relationships,       only: [:create, :destroy]
  resources :links
  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
		<div class="container" style="overflow: hidden;">
			 <nav class="navbar navbar-right">
				<li><%= link_to "le topo", letopo_path %></li>
				<li><%= link_to "faq...?", comment_path %></li>
				<li>pad général</li>
				<li>code source</li>
				<li>contacter</li>
			</nav>
		</div>  		
 </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		  <div class="container header-co">
			 <h5 style="border-bottom: solid 1px red;"><%= link_to "orama", root_path, id: "logo" %></h5>
			 <nav>
				<ul class="nav navbar-right">
					<% if logged_in? %>	
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Mon compte<b class="caret"></b></a>
						<ul class="dropdown-menu">
						<!--<li><%= link_to "#{}", current_user %></li> -->
							<!-- 'reglage' acces on 'mon espace only for orama'-->
							<li><%= link_to "réglage", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li><%= link_to "déconnexion", logout_path, method: :delete %></li>
						</ul>
					</li>
					<% else %>
						<li><h5 style="border-bottom: 1px solid red;"><%= link_to "se connecter", login_path %></h5></li>
					<% end %>
				</ul>
			</nav>
		</div>  		
  	</header>

  	<nav class="navbar navbar-right">
  		<div class="container" style="margin-bottom: 40px;">
  			<li><h1><%= link_to"catalogue", links_path %></h1></li>
			<li><h1><%= link_to "fabrique", fabrique_path %></h1></li>
			<li><h1><%= link_to "causerie", causeries_path %></h1></li>
  		</div>
  	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body>
     <%= render 'layouts/header'%>
    <div class="container">
    <% flash.each do |message_type, message| %>
    <!-- la ligne au dessus et en dessous affichent la meme chose -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>

    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>